If (_ZОН) and Комплексный_режим Then ONBU;
If (SОПДО) and Комплексный_режим Then OPODG;
If (ХРК07 And _ВКФБУ And ZРАСО_) and Комплексный_режим Then STRASO;
If (ХРК3D) and Комплексный_режим Then STPASO;
If (_ZВРАСО And  Not ZРАСО) and Комплексный_режим Then VKRASO;
If (_АСОНА And _АСОНВ And _ZРАСО And ZРАСО_) and Комплексный_режим Then ZAWRASO;
If (АСОНА_ And АСОНВ_) and Комплексный_режим Then NONASO;
If (ХРК5D Or H6235) and Комплексный_режим Then STTEN;
If (SТЕНЬ Or H6230) and Комплексный_режим Then ATTEN;
If (ХРК6D And _ВКФБУ) and Комплексный_режим Then HTTENRNS;
If (ZТРРУ_ And _ZРРУБУ) and Комплексный_режим Then RRU;
If (SРРУ) and Комплексный_режим Then ATRRU;
If (H6233) and Комплексный_режим Then HTRRU;
If (H6231) and Комплексный_режим Then STRNSO;
If (ХРКТР And ZЗТРЕВ_) and Комплексный_режим Then TREV;
If (ZТТРЕВ_ And _ZТРЕВБУ) and Комплексный_режим Then STTREV;
If (SТРЕВОГ) and Комплексный_режим Then ATTREV;
If (H6234) and Комплексный_режим Then HTTREV;
If (SВКСНА) and Комплексный_режим Then ATVKSNA;
If (SОБРК) and Комплексный_режим Then ATOBRK;
If (SОБРК) and Комплексный_режим Then ATOPRD;
If (SОБДО) and Комплексный_режим Then ATOBDO;
If (ХРК06 And _ВКФБУ) and Комплексный_режим Then ОRASO;
If (H6236) and Комплексный_режим Then ОBRKKU;
If (ХРК7С) and Комплексный_режим Then ОUDM;
If (ХРК4D Or H6270) and Комплексный_режим Then ОPS24BS;
If (H6271) and Комплексный_режим Then P1BHP;
If (H6272) and Комплексный_режим Then P2BHP;
If (ХРКA9) and Комплексный_режим Then OD12;
If (ХРКAA) and Комплексный_режим Then OD34;
If (ХРКAB) and Комплексный_режим Then OD56;
If (ХРКAC) and Комплексный_режим Then OKUD;
If (H6241) and Комплексный_режим Then OBSD;
If (ХРКAD) and Комплексный_режим Then VNGDO;
If (H6243) and Комплексный_режим Then VODO;
If (ХРКB0) and Комплексный_режим Then VRDO;
If (H6244) and Комплексный_режим Then VPD1;
If (H6245) and Комплексный_режим Then VPD2;
If (H6246) and Комплексный_режим Then VPD3;
If (H6247) and Комплексный_режим Then VPD4;
If (H620B) and Комплексный_режим Then VPD5;
If (H620A) and Комплексный_режим Then VPD6;
If (H624A) and Комплексный_режим Then VPDK1;
If (H624B) and Комплексный_режим Then VPDK2;
If (H624C) and Комплексный_режим Then VPDK3;
If (H624D) and Комплексный_режим Then VPDK4;
If (H624E) and Комплексный_режим Then VDND1;
If (H624F) and Комплексный_режим Then VDND2;
If (H6250) and Комплексный_режим Then VDND3;
If (H6251) and Комплексный_режим Then VDND4;
If (H6252) and Комплексный_режим Then VDND5;
If (H6253) and Комплексный_режим Then VDND6;
If (H6254) and Комплексный_режим Then VDNDK1;
If (H6255) and Комплексный_режим Then VDNDK2;
If (H6256) and Комплексный_режим Then VDNDK3;
If (H6257) and Комплексный_режим Then VDNDK4;
If (H6242) and Комплексный_режим Then ONDK;
If (H6258) and Комплексный_режим Then OND1;
If (H6259) and Комплексный_режим Then OND2;
If (H625A) and Комплексный_режим Then OND3;
If (H625B) and Комплексный_режим Then OND4;
If (H625C) and Комплексный_режим Then OND5;
If (H625D) and Комплексный_режим Then OND6;
If (H625E) and Комплексный_режим Then ONDO;
If (H625F) and Комплексный_режим Then VVIPD1;
If (H6260) and Комплексный_режим Then VVIPD2;
If (H6261) and Комплексный_режим Then VVIPD;
If (ZГК1_) and Комплексный_режим Then OGK1;
If (ZГК2_) and Комплексный_режим Then OGK2;
If (ZГК3_) and Комплексный_режим Then OGK3;
If (H62A0) and Комплексный_режим Then V1REK;
If (H62A1) and Комплексный_режим Then OREK;
If (H62A2) and Комплексный_режим Then OPNK;
If (SРНСО Or H6232) and Комплексный_режим Then ATRNSO;
If (ХРКТР And ZЗТРЕВ_) and Комплексный_режим Then TREVOG;
If (ZТРРУ_ And _ZРРУБУ) and Комплексный_режим Then SRRU;
If (H6200) and Комплексный_режим Then OBNFR;
If (_ZГК1) and Комплексный_режим Then STVGK1;
If (_ZГК2) and Комплексный_режим Then STVGK2;
If (_ZГК3) and Комплексный_режим Then STVGK3;
If (SГК1) and Комплексный_режим Then ATVGK1;
If (SГК2) and Комплексный_режим Then ATVGK2;
If (SГК3) and Комплексный_режим Then ATVGK3;
If (H5210) and Комплексный_режим Then TESTP;
If (H62B3) and Комплексный_режим Then TESTF;
