TÒÅÍÜ:Ttimer;
ÒĞÍÑÎ:Ttimer;
ÒĞĞÓ:Ttimer;
ÒÒĞÅÂÎÃ:Ttimer;
ÒÂÊÑÍÀ:Ttimer;
ÒÎÁĞÊ:Ttimer;
ÒÎÏÄÎ:Ttimer;
ÒÎÏĞÄ:Ttimer;
ÒÎÁÄÎ:Ttimer;
TÂÃÊ1:Ttimer;
TÂÃÊ2:Ttimer;
TÂÃÊ3:Ttimer;
Procedure TÒÅÍÜTimer(Sender: TObject);
Procedure ÒĞÍÑÎTimer(Sender: TObject);
Procedure ÒĞĞÓTimer(Sender: TObject);
Procedure ÒÒĞÅÂÎÃTimer(Sender: TObject);
Procedure ÒÂÊÑÍÀTimer(Sender: TObject);
Procedure ÒÎÁĞÊTimer(Sender: TObject);
Procedure ÒÎÏÄÎTimer(Sender: TObject);
Procedure ÒÎÏĞÄTimer(Sender: TObject);
Procedure ÒÎÁÄÎTimer(Sender: TObject);
Procedure TÂÃÊ1Timer(Sender: TObject);
Procedure TÂÃÊ2Timer(Sender: TObject);
Procedure TÂÃÊ3Timer(Sender: TObject);
